---
title: "Project Markdown"
author: Names
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library("dplyr")
library("ggplot2")
library("readr")
```

### Loading and editing the dataframe

```{r read-data}
dat <- read.csv(file = "data/numeric.csv", stringsAsFactors = F, header=TRUE) 

class(dat$concept3_E_1)

dat <- dat[-(1:2),]

dat <- dat %>%
  select(-IPAddress, -StartDate, -EndDate, -Status, -Duration..in.seconds., 
         -RecipientEmail, -ExternalReference, -RecipientFirstName, -RecipientLastName, 
         -LocationLatitude, -LocationLongitude, -DistributionChannel, -UserLanguage, -Agree, 
         -comments, -gender_6_TEXT, -RecordedDate, -ResponseId, -Progress, -Finished, -Q86, 
         -Q87, -Q88)

names(dat)

premedDat <- dat[c(4, 11),]
bioneuroDat <- dat[c(1, 2, 3, 7, 8, 14, 17, 20, 21, 22),]
engineeringDat <- dat[c(5, 12, 13),]
compsciDat <- dat[c(6, 10, 15, 16, 24),]
psychDat <- dat[c(9),]
econDat <- dat[c(18, 25, 26, 28),]
pubPolDat <- dat[c(23, 25, 27, 28),]
```

```{r means}
colMeans(premedDat)

```

